-- =============================================================
-- RISTORANTE PRO — Schema iniziale per Supabase (PostgreSQL)
-- Esegui questo script nel SQL Editor del tuo progetto Supabase:
-- https://supabase.com/dashboard/project/mpvqskyahvjmxrzfhaig/sql
-- =============================================================

-- ----------------------------------------------------------------
-- CATEGORIE
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.categorie (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome        TEXT    NOT NULL UNIQUE,
  icona       TEXT,
  descrizione TEXT,
  colore      TEXT    DEFAULT '#6366f1',
  ordine      INTEGER DEFAULT 0,
  user_id     TEXT,
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

-- ----------------------------------------------------------------
-- PIATTI
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.piatti (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome                TEXT    NOT NULL,
  descrizione         TEXT,
  prezzo              NUMERIC NOT NULL DEFAULT 0,
  tempo_preparazione  INTEGER DEFAULT 15,
  categoria_id        BIGINT  REFERENCES public.categorie(id) ON DELETE SET NULL,
  immagine            TEXT,
  disponibile         BOOLEAN NOT NULL DEFAULT TRUE,
  allergeni           TEXT,
  user_id             TEXT,
  updated_at          TIMESTAMPTZ DEFAULT NOW()
);

-- ----------------------------------------------------------------
-- INGREDIENTI
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ingredienti (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome          TEXT    NOT NULL UNIQUE,
  unita_misura  TEXT    NOT NULL DEFAULT 'kg',
  scorta        NUMERIC NOT NULL DEFAULT 0,
  scorta_min    NUMERIC NOT NULL DEFAULT 0,
  scadenza      DATE,
  prezzo_kg     NUMERIC DEFAULT 0,
  categoria     TEXT    DEFAULT 'Generici',
  fornitore     TEXT,
  user_id       TEXT,
  updated_at    TIMESTAMPTZ DEFAULT NOW()
);

-- ----------------------------------------------------------------
-- PIATTO_INGREDIENTI
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.piatto_ingredienti (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  piatto_id       BIGINT  NOT NULL REFERENCES public.piatti(id) ON DELETE CASCADE,
  ingrediente_id  BIGINT  NOT NULL REFERENCES public.ingredienti(id) ON DELETE CASCADE,
  quantita        NUMERIC NOT NULL DEFAULT 0,
  unita_misura    TEXT    NOT NULL DEFAULT 'g',
  user_id         TEXT,
  updated_at      TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(piatto_id, ingrediente_id)
);

-- ----------------------------------------------------------------
-- PERSONALE
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.personale (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome       TEXT    NOT NULL,
  cognome    TEXT    NOT NULL,
  ruolo      TEXT    NOT NULL DEFAULT 'cameriere',
  telefono   TEXT,
  email      TEXT,
  stipendio  NUMERIC NOT NULL DEFAULT 0,
  attivo     BOOLEAN NOT NULL DEFAULT TRUE,
  user_id    TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ----------------------------------------------------------------
-- TURNI
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.turni (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  personale_id  BIGINT  NOT NULL REFERENCES public.personale(id) ON DELETE CASCADE,
  data          DATE    NOT NULL,
  ora_inizio    TEXT    NOT NULL,
  ora_fine      TEXT    NOT NULL,
  ruolo_turno   TEXT,
  note          TEXT,
  user_id       TEXT,
  updated_at    TIMESTAMPTZ DEFAULT NOW()
);

-- ----------------------------------------------------------------
-- RICETTE
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ricette (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome                TEXT    NOT NULL,
  descrizione         TEXT,
  istruzioni          TEXT,
  tempo_preparazione  INTEGER DEFAULT 20,
  piatto_id           BIGINT  REFERENCES public.piatti(id) ON DELETE SET NULL,
  porzioni            INTEGER NOT NULL DEFAULT 1,
  note                TEXT,
  user_id             TEXT,
  updated_at          TIMESTAMPTZ DEFAULT NOW()
);

-- ----------------------------------------------------------------
-- RICETTA_INGREDIENTI
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ricetta_ingredienti (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ricetta_id      BIGINT  NOT NULL REFERENCES public.ricette(id) ON DELETE CASCADE,
  ingrediente_id  BIGINT  NOT NULL REFERENCES public.ingredienti(id) ON DELETE CASCADE,
  quantita        NUMERIC NOT NULL DEFAULT 0,
  unita_misura    TEXT    NOT NULL DEFAULT 'g',
  note            TEXT,
  user_id         TEXT,
  updated_at      TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(ricetta_id, ingrediente_id)
);

-- ----------------------------------------------------------------
-- MOVIMENTI_MAGAZZINO
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.movimenti_magazzino (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ingrediente_id BIGINT  NOT NULL REFERENCES public.ingredienti(id) ON DELETE CASCADE,
  tipo           TEXT    NOT NULL,
  quantita       NUMERIC NOT NULL DEFAULT 0,
  nota           TEXT,
  data_movimento TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  user_id        TEXT,
  updated_at     TIMESTAMPTZ DEFAULT NOW()
);

-- ----------------------------------------------------------------
-- ORDINI_FORNITORI
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ordini_fornitori (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fornitore               TEXT    NOT NULL,
  stato                   TEXT    NOT NULL DEFAULT 'inviato',
  data_ordine             DATE    NOT NULL,
  data_consegna_prevista  DATE,
  data_ricezione          DATE,
  note                    TEXT,
  totale                  NUMERIC NOT NULL DEFAULT 0,
  user_id                 TEXT,
  updated_at              TIMESTAMPTZ DEFAULT NOW()
);

-- ----------------------------------------------------------------
-- ORDINE_FORNITORE_RIGHE
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ordine_fornitore_righe (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ordine_id           BIGINT  NOT NULL REFERENCES public.ordini_fornitori(id) ON DELETE CASCADE,
  ingrediente_id      BIGINT  NOT NULL REFERENCES public.ingredienti(id) ON DELETE RESTRICT,
  quantita            NUMERIC NOT NULL DEFAULT 0,
  prezzo              NUMERIC NOT NULL DEFAULT 0,
  quantita_ricevuta   NUMERIC NOT NULL DEFAULT 0,
  totale              NUMERIC GENERATED ALWAYS AS (quantita * prezzo) STORED,
  user_id             TEXT,
  updated_at          TIMESTAMPTZ DEFAULT NOW()
);

-- ----------------------------------------------------------------
-- CODA_SYNC  (usata internamente dall'app per il sync offline)
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.coda_sync (
  id                TEXT    PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
  entita            TEXT    NOT NULL,
  record_id         TEXT    NOT NULL,
  azione            TEXT    NOT NULL,
  payload           TEXT,
  sincronizzato     BOOLEAN NOT NULL DEFAULT FALSE,
  stato             TEXT    NOT NULL DEFAULT 'pending',
  tentativi         INTEGER NOT NULL DEFAULT 0,
  ultimo_errore     TEXT,
  sincronizzato_il  TIMESTAMPTZ,
  user_id           TEXT,
  updated_at        TIMESTAMPTZ DEFAULT NOW()
);

-- ----------------------------------------------------------------
-- ROW LEVEL SECURITY — ogni utente vede solo i propri dati
-- ----------------------------------------------------------------
ALTER TABLE public.categorie            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.piatti               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ingredienti          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.piatto_ingredienti   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.personale            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.turni                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ricette              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ricetta_ingredienti  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.movimenti_magazzino  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ordini_fornitori     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ordine_fornitore_righe ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coda_sync            ENABLE ROW LEVEL SECURITY;

-- Policy generica: owner = auth.uid() oppure user_id corrispondente
DO $$
DECLARE
  t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'categorie','piatti','ingredienti','piatto_ingredienti',
    'personale','turni',
    'ricette','ricetta_ingredienti','movimenti_magazzino',
    'ordini_fornitori','ordine_fornitore_righe','coda_sync'
  ] LOOP
    -- Elimina la policy se esiste già, poi ricreala
    EXECUTE format('DROP POLICY IF EXISTS "owner_only" ON public.%I', t);
    EXECUTE format(
      'CREATE POLICY "owner_only" ON public.%I
       USING (user_id = auth.uid()::TEXT)
       WITH CHECK (user_id = auth.uid()::TEXT)', t
    );
  END LOOP;
END;
$$;
