-- =============================================================
-- RISTORANTE PRO — Migrazione aggiuntiva per menu e profiles
-- Non modifica le tabelle gia' definite nella migrazione iniziale.
-- =============================================================

-- ----------------------------------------------------------------
-- MENU
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.menu (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome        TEXT    NOT NULL,
  descrizione TEXT,
  tipo        TEXT    NOT NULL DEFAULT 'giornaliero',
  user_id     TEXT,
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

-- ----------------------------------------------------------------
-- MENU_VOCI
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.menu_voci (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  menu_id     BIGINT  NOT NULL REFERENCES public.menu(id) ON DELETE CASCADE,
  nome        TEXT    NOT NULL DEFAULT '',
  prezzo      NUMERIC NOT NULL DEFAULT 0,
  ordine      INTEGER NOT NULL DEFAULT 0,
  user_id     TEXT,
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

-- ----------------------------------------------------------------
-- PROFILES
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
  id          UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name   TEXT,
  avatar_url  TEXT,
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

-- ----------------------------------------------------------------
-- ROW LEVEL SECURITY
-- ----------------------------------------------------------------
ALTER TABLE public.menu ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_voci ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Policy generica: owner = auth.uid() oppure user_id corrispondente
DO $$
DECLARE
  t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'menu','menu_voci'
  ] LOOP
    EXECUTE format('DROP POLICY IF EXISTS "owner_only" ON public.%I', t);
    EXECUTE format('CREATE POLICY "owner_only" ON public.%I
      USING (user_id = auth.uid()::TEXT)
      WITH CHECK (user_id = auth.uid()::TEXT)', t);
  END LOOP;
END;
$$;

DROP POLICY IF EXISTS "profiles_self_access" ON public.profiles;
CREATE POLICY "profiles_self_access" ON public.profiles
  TO authenticated
  FOR ALL
  USING (id = auth.uid())
  WITH CHECK (id = auth.uid());
